export const CUISINE_DISPLAY = {
  
  'Italian': 'Italian',
  'Mediterranean': 'Mediterranean',
  'Japanese': 'Japanese',
  'Korean': 'Korean',
  'Chinese': 'Chinese',

  'Bistro': 'Bistro',
  'European': 'European',
  'African': 'African',
  'Asian': 'Asian',
  'Bakery & Pastry': 'Bakery',

  'Australian': 'Australian',
  'Bar & Pub': 'Pub',
  'British': 'British',
  'Brunch & Breakfast': 'Breakfast',
  'Buffet': 'Buffet',
  'Burgers': 'Burgers',
  'Cafe & Coffee': 'Cafe',
  'American': 'American',
  'Dessert & Ice Cream': 'Dessert',
  'Eastern European': 'Eastern European',

  'Family Restaurant': 'Family Restaurant',
  'Fast Food': 'Fast Food',
  'Fine Dining': 'Fine Dining',
  'French': 'French',
  'German': 'German',
  'Halal': 'Halal',
  'Kebab Shop': 'Kebab',
  'Latin American': 'Latin American',
  'Middle Eastern': 'Middle Eastern',
  'Northern European': 'Northern European',
  'Pizza': 'Pizza',
  'Sandwich & Deli': 'Deli',
  'Seafood': 'Seafood',
  'South Asian': 'South Asian',
  'Southeast Asian': 'Southeast Asian',
  'Southern European': 'Southern European',
  'Steakhouse & BBQ': 'Steakhouse',
  'Tapas': 'Tapas',
  'Unspecified': 'Unspecified',
  'Vegetarian & Vegan': 'Vegetarian',
};