export interface SampleCard {
    id: number;
    building: string;
    asset: string;
    zones: string[];
    simCounts: number[];
    status: string;
    time_category: string;
}

export const CARDS: SampleCard[] = [
  {
    id: 1,
    building: 'Tower 1', 
    asset: 'Hotel', 
    zones: ['Low', 'Mid', 'High'], 
    simCounts: [2, 2, 3], 
    status: 'Pending',
    time_category: 'Morning',
  },
  {
    id: 2,
    building: 'Tower 1',
    asset: 'Office',
    zones: ['Low', 'High'], 
    simCounts: [1, 2], 
    status: 'Pending',
    time_category: 'Afternoon',
  },
  {
    id: 3,
    building: 'Tower 2',
    asset: 'Office', 
    zones: ['Direct'], 
    simCounts: [1], 
    status: 'Accepted',
    time_category: 'Evening',
  }, 
  {
    id: 4,
    building: 'Tower 2',
    asset: 'Office', 
    zones: ['Low', 'High'], 
    simCounts: [1, 2],
    status: 'Archived',
    time_category: 'Evening',
  }, 
  {
    id: 5,
    building: 'Tower 1', 
    asset: 'Hotel', 
    zones: ['Low', 'Mid', 'High'], 
    simCounts: [2, 2, 3], 
    status: 'Accepted',
    time_category: 'Morning',
  },
  {
    id: 6,
    building: 'Tower 1',
    asset: 'Office',
    zones: ['Low', 'High'], 
    simCounts: [1, 2], 
    status: 'Accepted',
    time_category: 'Afternoon',
  },
  {
    id: 7,
    building: 'Tower 2',
    asset: 'Office', 
    zones: ['Direct'], 
    simCounts: [1], 
    status: 'Archived',
    time_category: 'Evening',
  }, 
  {
    id: 8,
    building: 'Tower 2',
    asset: 'Office', 
    zones: ['Low', 'High'], 
    simCounts: [1, 2],
    status: 'Pending',
    time_category: 'Evening',
  }, 
  {
    id: 9,
    building: 'Tower 1', 
    asset: 'Hotel', 
    zones: ['Low', 'Mid', 'High'], 
    simCounts: [2, 2, 3], 
    status: 'Accepted',
    time_category: 'Morning',
  },
  {
    id: 10,
    building: 'Tower 1',
    asset: 'Office',
    zones: ['Low', 'High'], 
    simCounts: [1, 2], 
    status: 'Accepted',
    time_category: 'Afternoon',
  },
  {
    id: 11,
    building: 'Tower 2',
    asset: 'Office', 
    zones: ['Direct'], 
    simCounts: [1], 
    status: 'Archived',
    time_category: 'Evening',
  }, 
  {
    id: 12,
    building: 'Tower 2',
    asset: 'Office', 
    zones: ['Low', 'High'], 
    simCounts: [1, 2],
    status: 'Pending',
    time_category: 'Evening',
  }, 
  {
    id: 13,
    building: 'Tower 1', 
    asset: 'Hotel', 
    zones: ['Low', 'Mid', 'High'], 
    simCounts: [2, 2, 3], 
    status: 'Accepted',
    time_category: 'Morning',
  },
  {
    id: 14,
    building: 'Tower 1',
    asset: 'Office',
    zones: ['Low', 'High'], 
    simCounts: [1, 2], 
    status: 'Accepted',
    time_category: 'Afternoon',
  },
  {
    id: 15,
    building: 'Tower 2',
    asset: 'Office', 
    zones: ['Direct'], 
    simCounts: [1], 
    status: 'Archived',
    time_category: 'Evening',
  }, 
  {
    id: 16,
    building: 'Tower 2',
    asset: 'Office', 
    zones: ['Low', 'High'], 
    simCounts: [1, 2],
    status: 'Pending',
    time_category: 'Evening',
  },
];
