export const MOBILE_BREAKPOINT = 960;
export const MOBILE_ENTER_BREAKPOINT = MOBILE_BREAKPOINT - 24;
export const MOBILE_EXIT_BREAKPOINT = MOBILE_BREAKPOINT + 24;

export const MOBILE_PEEK_PX = 72;
export const MOBILE_SNAP_MID_RATIO = 0.25;
export const MOBILE_SNAP_LARGE_RATIO = 0.5;
export const MOBILE_MAX_BOTTOM_GAP_PX = 90;

export const RESIZE_HEIGHT_JITTER_PX = 120;
export const RESIZE_WIDTH_JITTER_PX = 16;
export const COARSE_POINTER_QUERY = '(pointer: coarse)';